apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: cows
spec:
  rules:
  - host: cows.ijmacd.com
    http:
      paths:
      - backend:
          service:
            name: cows
            port:
              number: 80
        path: /
        pathType: Prefix
